name: Build and Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files
          uses: picodebr/copy-action@v1
          with:
            ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
            ssh_user: ${{ secrets.SSH_USER }}
            ssh_host: ${{ secrets.SSH_HOST }}
            source: "."
            destination: "~/app"

      - name: Run Docker Compose on VPS
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd /app && docker-compose down && docker-compose -f docker-compose.yml -f production.yml -f dbadmin.yml up --build'

